apiVersion: 1

datasources:
  - name: Berlin Events Postgres
    uid: berlin-events-postgres
    type: postgres
    access: proxy
    url: postgres_db:5432
    database: postgres
    user: grafana_ro
    secureJsonData:
      password: $__env{GRAFANA_RO_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false
    editable: false
